# Generated by Django 4.1.4 on 2022-12-19 21:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('headerimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('postdate', models.DateField(auto_now_add=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('snippet', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categories')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.label')),
            ],
        ),
    ]
