# Generated by Django 4.1.4 on 2022-12-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headerimage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
