# Generated by Django 4.1.4 on 2022-12-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
