# Generated by Django 4.1.4 on 2023-01-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='postdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
